import unittest
from unittest.mock import patch

from social_content_extractor import cli as main


SAMPLE_DATA = {
    "url": "https://www.instagram.com/p/ABC123/",
    "owner": {"username": "tester"},
    "post_type": "carousel",
    "date": "2026-03-01T00:00:00",
    "date_local": None,
    "likes": 1,
    "comments_count": 2,
    "media_count": 1,
    "caption": "",
    "accessibility_caption": "Autogenerated summary",
    "hashtags": [],
    "mentions": [],
    "media": [{"index": 1, "type": "image"}],
    "slides": [],
    "ocr_text": [],
}

YOUTUBE_SAMPLE_DATA = {
    **SAMPLE_DATA,
    "platform": "youtube",
    "url": "https://www.youtube.com/shorts/Fh7SAaWZ-cQ",
    "title": "Short title",
}


class CLITests(unittest.TestCase):
    @patch.object(main.console, "print")
    def test_display_results_hides_accessibility_caption_by_default(self, mock_print) -> None:
        main.display_results(SAMPLE_DATA)

        printed_titles = [
            call.args[0].title
            for call in mock_print.call_args_list
            if call.args and hasattr(call.args[0], "title")
        ]
        self.assertNotIn("Accessibility Caption", printed_titles)

    @patch.object(main.console, "print")
    def test_display_results_shows_accessibility_caption_when_enabled(self, mock_print) -> None:
        main.display_results(SAMPLE_DATA, show_accessibility=True)

        printed_titles = [
            call.args[0].title
            for call in mock_print.call_args_list
            if call.args and hasattr(call.args[0], "title")
        ]
        self.assertIn("Accessibility Caption", printed_titles)

    @patch.object(main.console, "print")
    def test_display_results_uses_social_header_for_shorts(self, mock_print) -> None:
        main.display_results(YOUTUBE_SAMPLE_DATA)

        header_panels = [
            call.args[0]
            for call in mock_print.call_args_list
            if call.args and getattr(call.args[0], "renderable", None)
        ]
        self.assertTrue(header_panels)
        self.assertIn("Social Content Extractor", str(header_panels[0].renderable))


if __name__ == "__main__":
    unittest.main()
